---
dependency:
  name: "galaxy"
driver:
  name: "docker"
platforms:
  -
    name: "molecule-almalinux"
    image: "docker.io/almalinux:9"
    commands:
      - "dnf makecache"
      - >-
          dnf --assumeyes install
          bash
          iproute
          python3-devel
          sudo
  -
    name: "molecule-fedora"
    image: "docker.io/fedora:41"
    commands:
      - "dnf makecache"
      - >-
          dnf --assumeyes install
          iproute
          python3-devel
          python3-libdnf5
          sudo
provisioner:
  name: "ansible"
verifier:
  name: "ansible"
